const fixelDisplay = '"Fixel Display", "Fixel Text", sans-serif';
const fixelText = '"Fixel Text", sans-serif';

export const brandSize = {
  height: 48,
  width: 179,
} as const;

export const variantTheme = {
  color: {
    backgroundCriticalFaded: { hex: '#fee4e2' },
    backgroundDisabled: { hex: '#d0d5dd' },
    backgroundDisabledFaded: { hex: '#f2f4f7' },
    backgroundElevationBase: { hex: '#ffffff' },
    backgroundElevationOverlay: { hex: '#ffffff' },
    backgroundElevationRaised: { hex: '#ffffff' },
    backgroundNeutral: { hex: '#101828' },
    backgroundNeutralFaded: { hex: '#f2f4f7' },
    backgroundPage: { hex: '#ffffff' },
    backgroundPageFaded: { hex: '#f2f4f7' },
    backgroundPositive: { hex: '#12b76a' },
    backgroundPositiveFaded: { hex: '#edfcf2' },
    backgroundPrimary: { hex: '#087443' },
    backgroundPrimaryFaded: { hex: '#d3f8df' },
    backgroundPrimaryHighlighted: { hex: '#06613a' },
    black: { hex: '#101828' },
    borderCritical: { hex: '#fda29b' },
    borderCriticalFaded: { hex: '#fee4e2' },
    borderDisabled: { hex: '#d0d5dd' },
    borderNeutral: { hex: '#d0d5dd' },
    borderNeutralFaded: { hex: '#eaecf0' },
    borderPositive: { hex: '#12b76a' },
    borderPrimary: { hex: '#73e2a3' },
    borderPrimaryFaded: { hex: '#d3f8df' },
    errorRing: { hex: '#fee4e2' },
    foregroundCritical: { hex: '#f04438' },
    foregroundDisabled: { hex: '#98a2b3' },
    foregroundNeutral: { hex: '#101828' },
    foregroundNeutralFaded: { hex: '#667085' },
    foregroundPositive: { hex: '#12b76a' },
    foregroundPrimary: { hex: '#087443' },
    onBackgroundPrimary: { hex: '#ffffff' },
    progressIncomplete: { hex: '#1018283d' },
    successBadge: { hex: '#d1fadf' },
    textSubtle: { hex: '#475467' },
    white: { hex: '#ffffff' },
  },
  duration: {
    reducedMotion: { ms: 1 },
    spinner: { ms: 800 },
  },
  font: {
    body1: {
      fontFamilyToken: 'body',
      fontSize: { px: 16 },
      fontWeightToken: 'regular',
      lineHeight: { px: 24 },
    },
    body2: {
      fontFamilyToken: 'body',
      fontSize: { px: 14 },
      fontWeightToken: 'regular',
      lineHeight: { px: 20 },
    },
    featured1: {
      fontFamilyToken: 'title',
      fontSize: { px: 36 },
      fontWeightToken: 'semibold',
      letterSpacing: { px: -0.72 },
      lineHeight: { px: 44 },
    },
    featured6: {
      fontFamilyToken: 'title',
      fontSize: { px: 18 },
      fontWeightToken: 'semibold',
      lineHeight: { px: 28 },
    },
    headline1: {
      fontFamilyToken: 'headline',
      fontSize: { px: 48 },
      fontWeightToken: 'semibold',
      letterSpacing: { px: -0.96 },
      lineHeight: { px: 60 },
    },
    headline2: {
      fontFamilyToken: 'headline',
      fontSize: { px: 36 },
      fontWeightToken: 'semibold',
      letterSpacing: { px: -0.72 },
      lineHeight: { px: 44 },
    },
  },
  fontFamily: {
    body: { family: fixelText },
    headline: { family: fixelDisplay },
    monospace: { family: fixelText },
    title: { family: fixelDisplay },
  },
  radius: {
    large: { px: 12 },
    medium: { px: 6 },
    small: { px: 4 },
  },
  shadow: {
    control: {
      parts: [
        {
          blurRadius: 2,
          colorToken: 'black',
          offsetX: 0,
          offsetY: 1,
          opacity: 0.05,
          spreadRadius: 0,
        },
      ],
    },
  },
  unit: {
    base: { px: 4 },
    borderWidth: { px: 1 },
    brandHeight: { px: brandSize.height },
    brandWidth: { px: brandSize.width },
    buttonHeightLarge: { px: 60 },
    buttonHeightMedium: { px: 44 },
    buttonPaddingLargeHorizontal: { px: 27 },
    buttonPaddingLargeVertical: { px: 15 },
    buttonPaddingMediumHorizontal: { px: 17 },
    buttonPaddingMediumVertical: { px: 9 },
    canvasWidth: { px: 1440 },
    contentWidth: { px: 1120 },
    controlHeight: { px: 40 },
    controlPaddingHorizontal: { px: 11 },
    controlPaddingVertical: { px: 7 },
    focusOffset: { px: 1 },
    iconSize: { px: 20 },
    progressSize: { px: 8 },
    mobileBrandWidth: { px: 143.2 },
    mobilePageBottom: { px: 64 },
    mobilePageGutter: { px: 16 },
    mobilePageTop: { px: 20 },
    pageBottom: { px: 120 },
    pageGutter: { px: 160 },
    pageTop: { px: 32 },
    panelHeight: { px: 600 },
    panelHeightMobile: { px: 420 },
    sectionHeaderHeight: { px: 76 },
    successBadgeSize: { px: 28 },
    textareaContentHeight: { px: 234 },
    textareaHeight: { px: 236 },
    textareaPaddingHorizontal: { px: 13 },
    textareaPaddingVertical: { px: 11 },
  },
  viewport: {
    l: { minPx: 900 },
    m: { minPx: 768 },
    xl: { minPx: 1280 },
  },
};
