/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as FakeRouteImport } from './routes/fake'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiGenerateRouteImport } from './routes/api.generate'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications.$applicationId'
import { Route as ApplicationsNewRouteImport } from './routes/applications.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeRoute = FakeRouteImport.update({
  id: '/fake',
  path: '/fake',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRoute,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => ApplicationsRoute,
  } as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/fake': typeof FakeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/': typeof ApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/fake': typeof FakeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications': typeof ApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/fake': typeof FakeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/': typeof ApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/applications'
    | '/fake'
    | '/sitemap.xml'
    | '/api/generate'
    | '/api/health'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/fake'
    | '/sitemap.xml'
    | '/api/generate'
    | '/api/health'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/applications'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/applications'
    | '/fake'
    | '/sitemap.xml'
    | '/api/generate'
    | '/api/health'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  FakeRoute: typeof FakeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake': {
      id: '/fake'
      path: '/fake'
      fullPath: '/fake'
      preLoaderRoute: typeof FakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof ApplicationsRoute
    }
  }
}

interface ApplicationsRouteChildren {
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  FakeRoute: FakeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
